# Docker Compose for KPFU LLM Generator

services:
  # PostgreSQL database for metadata and citations
  postgres:
    image: postgres:15-alpine
    container_name: kpfu-postgres
    environment:
      POSTGRES_DB: kpfu_generator
      POSTGRES_USER: kpfu_user
      POSTGRES_PASSWORD: kpfu_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Redis for multi-layer caching
  redis:
    image: redis:7-alpine
    container_name: kpfu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M

  # ChromaDB vector database
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.18
    container_name: kpfu-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Ollama service for LLM
  ollama:
    image: ollama/ollama:latest
    container_name: kpfu-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 1G

  # Main application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kpfu-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://kpfu_user:kpfu_password@postgres:5432/kpfu_generator
      - REDIS_URL=redis://redis:6379
      - CHROMADB_URL=http://chromadb:8000
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - postgres
      - redis
      - chromadb
      - ollama
    volumes:
      - ./app:/app
      - model_cache:/app/models
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

volumes:
  postgres_data:
  redis_data:
  chromadb_data:
  ollama_data:
  model_cache: